<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Iyu.Conventions.Testing\Iyu.Conventions.Testing.csproj" />
    <ProjectReference Include="..\Fixtures.Defective\Iyu.Conventions.Testing.Fixtures.Defective.csproj" />
    <ProjectReference Include="..\Fixtures.Clean\Iyu.Conventions.Testing.Fixtures.Clean.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" Version="2.3.3" />
  </ItemGroup>

</Project>
